// Code generated by protoc-gen-go.
// source: protos/golang.conradwood.net/apis/secureargs/secureargs.proto
// DO NOT EDIT!

/*
Package secureargs is a generated protocol buffer package.

It is generated from these files:
	protos/golang.conradwood.net/apis/secureargs/secureargs.proto

It has these top-level messages:
	GetArgsRequest
	ArgsResponse
	SetArgRequest
	Arg
*/
package secureargs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "golang.conradwood.net/apis/common"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetArgsRequest struct {
	RepositoryID uint64 `protobuf:"varint,1,opt,name=RepositoryID" json:"RepositoryID,omitempty"`
	ArtefactID   uint64 `protobuf:"varint,2,opt,name=ArtefactID" json:"ArtefactID,omitempty"`
}

func (m *GetArgsRequest) Reset()                    { *m = GetArgsRequest{} }
func (m *GetArgsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetArgsRequest) ProtoMessage()               {}
func (*GetArgsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetArgsRequest) GetRepositoryID() uint64 {
	if m != nil {
		return m.RepositoryID
	}
	return 0
}

func (m *GetArgsRequest) GetArtefactID() uint64 {
	if m != nil {
		return m.ArtefactID
	}
	return 0
}

type ArgsResponse struct {
	Args map[string]string `protobuf:"bytes,1,rep,name=Args" json:"Args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ArgsResponse) Reset()                    { *m = ArgsResponse{} }
func (m *ArgsResponse) String() string            { return proto.CompactTextString(m) }
func (*ArgsResponse) ProtoMessage()               {}
func (*ArgsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ArgsResponse) GetArgs() map[string]string {
	if m != nil {
		return m.Args
	}
	return nil
}

type SetArgRequest struct {
	RepositoryID uint64 `protobuf:"varint,1,opt,name=RepositoryID" json:"RepositoryID,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Value        string `protobuf:"bytes,3,opt,name=Value" json:"Value,omitempty"`
	ArtefactID   uint64 `protobuf:"varint,4,opt,name=ArtefactID" json:"ArtefactID,omitempty"`
}

func (m *SetArgRequest) Reset()                    { *m = SetArgRequest{} }
func (m *SetArgRequest) String() string            { return proto.CompactTextString(m) }
func (*SetArgRequest) ProtoMessage()               {}
func (*SetArgRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SetArgRequest) GetRepositoryID() uint64 {
	if m != nil {
		return m.RepositoryID
	}
	return 0
}

func (m *SetArgRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetArgRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SetArgRequest) GetArtefactID() uint64 {
	if m != nil {
		return m.ArtefactID
	}
	return 0
}

// not very normalized database....
type Arg struct {
	ID uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	// string Repository = 2; // obsolete, use ID instead
	Name         string `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Value        string `protobuf:"bytes,4,opt,name=Value" json:"Value,omitempty"`
	RepositoryID uint64 `protobuf:"varint,5,opt,name=RepositoryID" json:"RepositoryID,omitempty"`
	ArtefactID   uint64 `protobuf:"varint,6,opt,name=ArtefactID" json:"ArtefactID,omitempty"`
}

func (m *Arg) Reset()                    { *m = Arg{} }
func (m *Arg) String() string            { return proto.CompactTextString(m) }
func (*Arg) ProtoMessage()               {}
func (*Arg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Arg) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Arg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Arg) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Arg) GetRepositoryID() uint64 {
	if m != nil {
		return m.RepositoryID
	}
	return 0
}

func (m *Arg) GetArtefactID() uint64 {
	if m != nil {
		return m.ArtefactID
	}
	return 0
}

func init() {
	proto.RegisterType((*GetArgsRequest)(nil), "secureargs.GetArgsRequest")
	proto.RegisterType((*ArgsResponse)(nil), "secureargs.ArgsResponse")
	proto.RegisterType((*SetArgRequest)(nil), "secureargs.SetArgRequest")
	proto.RegisterType((*Arg)(nil), "secureargs.Arg")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SecureArgsService service

type SecureArgsServiceClient interface {
	// get all arguments for a given repository
	GetArgs(ctx context.Context, in *GetArgsRequest, opts ...grpc.CallOption) (*ArgsResponse, error)
	// set an arg
	SetArg(ctx context.Context, in *SetArgRequest, opts ...grpc.CallOption) (*common.Void, error)
}

type secureArgsServiceClient struct {
	cc *grpc.ClientConn
}

func NewSecureArgsServiceClient(cc *grpc.ClientConn) SecureArgsServiceClient {
	return &secureArgsServiceClient{cc}
}

func (c *secureArgsServiceClient) GetArgs(ctx context.Context, in *GetArgsRequest, opts ...grpc.CallOption) (*ArgsResponse, error) {
	out := new(ArgsResponse)
	err := grpc.Invoke(ctx, "/secureargs.SecureArgsService/GetArgs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secureArgsServiceClient) SetArg(ctx context.Context, in *SetArgRequest, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/secureargs.SecureArgsService/SetArg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SecureArgsService service

type SecureArgsServiceServer interface {
	// get all arguments for a given repository
	GetArgs(context.Context, *GetArgsRequest) (*ArgsResponse, error)
	// set an arg
	SetArg(context.Context, *SetArgRequest) (*common.Void, error)
}

func RegisterSecureArgsServiceServer(s *grpc.Server, srv SecureArgsServiceServer) {
	s.RegisterService(&_SecureArgsService_serviceDesc, srv)
}

func _SecureArgsService_GetArgs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArgsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureArgsServiceServer).GetArgs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secureargs.SecureArgsService/GetArgs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureArgsServiceServer).GetArgs(ctx, req.(*GetArgsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecureArgsService_SetArg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetArgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureArgsServiceServer).SetArg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secureargs.SecureArgsService/SetArg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureArgsServiceServer).SetArg(ctx, req.(*SetArgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SecureArgsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "secureargs.SecureArgsService",
	HandlerType: (*SecureArgsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArgs",
			Handler:    _SecureArgsService_GetArgs_Handler,
		},
		{
			MethodName: "SetArg",
			Handler:    _SecureArgsService_SetArg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/golang.conradwood.net/apis/secureargs/secureargs.proto",
}

func init() {
	proto.RegisterFile("protos/golang.conradwood.net/apis/secureargs/secureargs.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x53, 0xcf, 0x4b, 0xeb, 0x40,
	0x10, 0x26, 0x3f, 0xda, 0x47, 0xe7, 0xf5, 0x95, 0xe7, 0xe2, 0x21, 0xe6, 0x20, 0x25, 0x50, 0xe8,
	0x29, 0xc5, 0x0a, 0x2a, 0x82, 0x48, 0xa5, 0x22, 0xbd, 0xf4, 0x90, 0x4a, 0x0f, 0xde, 0xd6, 0x74,
	0x0c, 0xc1, 0x76, 0x37, 0xee, 0x6e, 0x2b, 0x3d, 0x88, 0x07, 0x0f, 0xfe, 0xdb, 0x92, 0x4d, 0xac,
	0xdb, 0xfa, 0xfb, 0x94, 0x99, 0x61, 0x76, 0xbe, 0xf9, 0xe6, 0xfb, 0x02, 0x27, 0x99, 0xe0, 0x8a,
	0xcb, 0x4e, 0xc2, 0xa7, 0x94, 0x25, 0x61, 0xcc, 0x99, 0xa0, 0x93, 0x7b, 0xce, 0x27, 0x21, 0x43,
	0xd5, 0xa1, 0x59, 0x2a, 0x3b, 0x12, 0xe3, 0xb9, 0x40, 0x2a, 0x12, 0x33, 0x0c, 0xf5, 0x3b, 0x02,
	0x6f, 0x15, 0x3f, 0xfc, 0x62, 0x46, 0xcc, 0x67, 0x33, 0xce, 0xca, 0x4f, 0xf1, 0x36, 0xb8, 0x84,
	0xc6, 0x05, 0xaa, 0x9e, 0x48, 0x64, 0x84, 0x77, 0x73, 0x94, 0x8a, 0x04, 0x50, 0x8f, 0x30, 0xe3,
	0x32, 0x55, 0x5c, 0x2c, 0x07, 0x7d, 0xcf, 0x6a, 0x5a, 0x6d, 0x37, 0x5a, 0xab, 0x91, 0x5d, 0x80,
	0x9e, 0x50, 0x78, 0x43, 0x63, 0x35, 0xe8, 0x7b, 0xb6, 0xee, 0x30, 0x2a, 0xc1, 0x23, 0xd4, 0x8b,
	0x91, 0x32, 0xe3, 0x4c, 0x22, 0x39, 0x00, 0x37, 0xcf, 0x3d, 0xab, 0xe9, 0xb4, 0xff, 0x76, 0x83,
	0xd0, 0xa0, 0x60, 0xf6, 0xe9, 0xe4, 0x9c, 0x29, 0xb1, 0x8c, 0x74, 0xbf, 0x7f, 0x08, 0xb5, 0x55,
	0x89, 0xfc, 0x07, 0xe7, 0x16, 0x97, 0x7a, 0x9f, 0x5a, 0x94, 0x87, 0x64, 0x1b, 0x2a, 0x0b, 0x3a,
	0x9d, 0xa3, 0xde, 0xa0, 0x16, 0x15, 0xc9, 0xb1, 0x7d, 0x64, 0x05, 0x0f, 0xf0, 0x6f, 0xa4, 0x69,
	0xfd, 0x86, 0x15, 0x01, 0x77, 0x48, 0x67, 0xaf, 0xd3, 0x74, 0x9c, 0x43, 0x8c, 0x35, 0x84, 0x53,
	0x40, 0xe8, 0x64, 0x83, 0xbf, 0xfb, 0x8e, 0xff, 0x93, 0x05, 0x4e, 0x4f, 0x24, 0xa4, 0x01, 0xf6,
	0x0a, 0xcb, 0x36, 0x10, 0x9c, 0x8f, 0x10, 0x5c, 0x13, 0x61, 0x73, 0xdf, 0xca, 0xb7, 0x2a, 0x54,
	0x37, 0xb7, 0xe8, 0x3e, 0x5b, 0xb0, 0x35, 0xd2, 0x97, 0xce, 0x8f, 0x38, 0x42, 0xb1, 0x48, 0x63,
	0x24, 0xa7, 0xf0, 0xa7, 0x54, 0x9c, 0xf8, 0xa6, 0x10, 0xeb, 0x36, 0xf0, 0xbd, 0xcf, 0x44, 0x22,
	0x7b, 0x50, 0x2d, 0x6e, 0x4b, 0x76, 0xcc, 0x9e, 0xb5, 0x7b, 0xfb, 0xf5, 0xb0, 0xb4, 0xd9, 0x98,
	0xa7, 0x93, 0xb3, 0x21, 0xb4, 0x18, 0x2a, 0xd3, 0x94, 0xa5, 0x4d, 0x73, 0x5f, 0x1a, 0x43, 0xae,
	0x5a, 0x3f, 0xfa, 0x05, 0xae, 0xab, 0xda, 0xbc, 0xfb, 0x2f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x43,
	0x2b, 0x12, 0x5d, 0x39, 0x03, 0x00, 0x00,
}





